name: ADA build and deploy

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  build-landscape:
    uses: cncf/landscape2-sites/.github/workflows/build-and-deploy.yml@main
    with:
      foundation: ada
      repository: appdefensealliance/landscape
    secrets: inherit
