name: Camara build and deploy

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  build-landscape:
    uses: cncf/landscape2-sites/.github/workflows/build-and-deploy.yml@main
    with:
      foundation: camara
      repository: cynthia-sg/camara-landscape
    secrets: inherit
