name: CDF build and deploy

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  build-landscape:
    uses: cncf/landscape2-sites/.github/workflows/build-and-deploy.yml@main
    with:
      foundation: cdf
      repository: cdfoundation/cdf-landscape
    secrets: inherit
