name: CDF

on:
  push:
    branches:
      - main
    paths:
      - cdf/**
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  build-landscape:
    uses: cncf/landscape2-sites/.github/workflows/build-and-deploy.yml@main
    with:
      foundation: cdf
      repository: cdfoundation/cdf-landscape
    concurrency:
      group: build-and-deploy
    secrets: inherit
