name: CNCF settings validation

on:
  pull_request:
    branches:
      - main
    paths:
      - cncf/settings.yml

jobs:
  validate-landscape-settings:
    runs-on: ubuntu-latest
    name: "Validate landscape settings file"
    steps:
      - uses: actions/checkout@v3
      - uses: cncf/landscape2-validate-action@v2
        with:
          target_kind: settings
          target_path: cncf/settings.yml
