name: CNCF
on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  build-landscape:
    uses: tegioz/landscape2-sites/.github/workflows/build-and-deploy.yml@main
    with:
      foundation: cncf
      repository: cncf/landscape
      s3_bucket: landscape2-prototype-demo
    secrets: inherit
