name: CNCF

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * *"

jobs:
  build-landscape:
    uses: cncf/landscape2-sites/.github/workflows/build-and-deploy.yml@main
    with:
      foundation: cncf
      repository: cncf/landscape
    secrets: inherit
