name: CNCF

on:
  push:
    branches:
      - main
    paths:
      - cncf/**
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  build-landscape:
    uses: cncf/landscape2-sites/.github/workflows/build-and-deploy.yml@main
    with:
      foundation: cncf
      repository: cncf/landscape
    secrets: inherit
