name: CNCF
on:
  push:
    branches:
      - main

jobs:
  build-landscape:
    uses: tegioz/landscape2-sites/.github/workflows/build-and-deploy.yml@main
    with:
      foundation: cncf
      repository: cncf/landscape
      s3_bucket: landscape2-prototype-demo
    secrets:
      GH_TOKENS: ${{ secrets.GH_TOKENS }}
      CRUNCHBASE_API_KEY: ${{ secrets.CRUNCHBASE_API_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}