name: DLT build and deploy

on:
  # schedule:
  #   - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  build-landscape:
    uses: cncf/landscape2-sites/.github/workflows/build-and-deploy.yml@main
    with:
      foundation: dlt
      repository: hyperledger-dlt-landscape/hyperledger-dlt-landscape
    secrets: inherit
