name: DLT

on:
  push:
    branches:
      - main
    paths:
      - dlt/**
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  build-landscape:
    uses: cncf/landscape2-sites/.github/workflows/build-and-deploy.yml@main
    with:
      foundation: dlt
      repository: hyperledger-dlt-landscape/hyperledger-dlt-landscape
    concurrency:
      group: build-and-deploy
    secrets: inherit
