name: LF build and deploy

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
    inputs:
      runner:
        description: "Runner"
        type: string
        required: false
        default: ubuntu-latest-16-cores

jobs:
  build-landscape:
    uses: cncf/landscape2-sites/.github/workflows/build-and-deploy.yml@main
    with:
      foundation: lf
      repository: jmertic/lf-landscape
      runner: ${{ github.event.inputs.runner }}
    secrets: inherit
