name: LF build and deploy

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build-landscape:
    uses: cncf/landscape2-sites/.github/workflows/build-and-deploy.yml@main
    with:
      foundation: lf
      repository: jmertic/lf-landscape
      runner: equinix-16cpu-64gb
    secrets: inherit
