name: LFEnergy build and deploy

on:
  # schedule:
  #   - cron: "0 21 * * *"
  workflow_dispatch:

jobs:
  build-landscape:
    uses: cncf/landscape2-sites/.github/workflows/build-and-deploy.yml@main
    with:
      foundation: lfenergy
      repository: lf-energy/lfenergy-landscape
    secrets: inherit
