name: O3DF build and deploy

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build-landscape:
    uses: cncf/landscape2-sites/.github/workflows/build-and-deploy.yml@main
    with:
      foundation: o3df
      repository: Open3DFoundation/o3df-landscape
    secrets: inherit
