name: OAI build and deploy

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  build-landscape:
    uses: cncf/landscape2-sites/.github/workflows/build-and-deploy.yml@main
    with:
      foundation: oai
      repository: OAI/landscape
    secrets: inherit
