name: OMP build and deploy

on:
  # schedule:
  #   - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build-landscape:
    uses: cncf/landscape2-sites/.github/workflows/build-and-deploy.yml@main
    with:
      foundation: omp
      repository: openmainframeproject/omp-landscape
    secrets: inherit
