name: OpenSSF

on:
  push:
    branches:
      - main
    paths:
      - openssf/**
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  build-landscape:
    uses: cncf/landscape2-sites/.github/workflows/build-and-deploy.yml@main
    with:
      foundation: openssf
      repository: ossf/ossf-landscape
    concurrency:
      group: build-and-deploy
    secrets: inherit
