name: Overture Maps build and deploy

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build-landscape:
    uses: cncf/landscape2-sites/.github/workflows/build-and-deploy.yml@main
    with:
      foundation: overturemaps
      repository: OvertureMaps/landscape
    secrets: inherit
