name: Presto

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

jobs:
  build-landscape:
    uses: cncf/landscape2-sites/.github/workflows/build-and-deploy.yml@main
    with:
      foundation: presto
      repository: prestodb/presto-landscape
    secrets: inherit
